(add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp/third-party"))

(load "static-configuration.el")
(das-clear-up-ui)
(das-everything-in-utf8)
(das-initialize-fonts)
(das-initialize-package)
(das-miscellaneous-settings)
(das-set-special-directories)
(das-unprotect-commands)
(das-initialize-global-hooks)
(das-import-path)
(das-initialize-env-variables)

(load "colors.el")
(das-install-color-theme)

(load "modes-and-styles.el")
(das-initialize-modes)  
(das-initialize-styles)

(das-initialize-c-mode)
(das-initialize-ido-mode)
(das-initialize-lisp-mode)
(das-initialize-text-mode)
(das-initialize-haskell-mode)
(das-initialize-rust-mode)
(das-initialize-magit-mode)
(das-initialize-p4-mode)
(das-initialize-tramp-mode)
(das-initialize-agda-mode)
(das-initialize-rcirc-mode)

(load "utilities.el")
(das-initialize-utilities)

(load "keybindings.el")
(das-initialize-keybindings)

(setq custom-file "~/.emacs.d/lisp/custom-variables.el")
(load custom-file)
